# Generated by Django 5.0.6 on 2024-05-20 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MesaServicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoNombre', models.CharField(db_comment='Nombre del tipo de Procedimiento', max_length=20)),
                ('tipDescripcion', models.TextField(db_comment='Texto con la descripcion del procedimiento', max_length=100)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True, db_comment='Fecha y Hora del Registro')),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True, db_comment='Fecha y Hora última actualizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solDescripcion', models.TextField(db_comment='Texto que describe la solicitud del empleado', max_length=1000)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True, db_comment='Fecha y Hora del Registro')),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True, db_comment='Fecha y Hora última actualizacion')),
                ('solOficinaAmbiente', models.ForeignKey(db_comment='Hace referencia a la oficina o ambiente donde se encuentra el equipo', on_delete=django.db.models.deletion.PROTECT, to='MesaServicios.oficinaambiente')),
                ('solUsuario', models.ForeignKey(db_comment='Hace referencia al empleado que hace la solicitud', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Casos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casCodigo', models.CharField(db_comment='Codigo único del caso', max_length=10, unique=True)),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True, db_comment='Fecha y Hora última actualizacion')),
                ('casUsuario', models.ForeignKey(db_comment='Empleado de soperte tecnico asignado al caso', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('casSolicitud', models.ForeignKey(db_comment='Hace referencia a la solicitud que genera', on_delete=django.db.models.deletion.PROTECT, to='MesaServicios.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='SolucionCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solProcedimiento', models.TextField(db_comment='Texto del procedimiento realizado en la solución del caso', max_length=2000)),
                ('solTipoSolucion', models.CharField(choices=[('Parcial', 'Parcial'), ('Definitiva', 'Definitiva')], db_comment='Tipo de la solución, si es parcial o definitiva', max_length=20)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True, db_comment='Fecha y hora del registro')),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True, db_comment='Fecha y hora última actualización')),
                ('solCaso', models.ForeignKey(db_comment='Hace referencia al caso que genera la solución', on_delete=django.db.models.deletion.PROTECT, to='MesaServicios.casos')),
            ],
        ),
        migrations.CreateModel(
            name='SolucionCasoTipoProcedimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solSolucionCaso', models.ForeignKey(db_comment='Hace referencia a la solución del Caso', on_delete=django.db.models.deletion.PROTECT, to='MesaServicios.solucioncaso')),
                ('solTipoProcedimiento', models.ForeignKey(db_comment='Hace referencia al tipo de procedimiento de la solución', on_delete=django.db.models.deletion.PROTECT, to='MesaServicios.tipoprocedimiento')),
            ],
        ),
    ]
