# Generated by Django 4.2.13 on 2024-05-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMesaDeServicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casos',
            name='casEstado',
            field=models.CharField(choices=[('Solicitad', 'Solicitad'), ('En Proceso', 'En Preceso'), ('Finalizado', 'Finalizado')], db_comment='', default='solicitada', max_length=15),
        ),
    ]
